# Tests if the typescript project builds without erroring
name: 'build'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: NPM install
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm install

      - name: NPM Build
        run: npm run build