version: '3.8'

services:
  app:
    build: .
    container_name: mvp_app
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - TELNYX_API_KEY=${TELNYX_API_KEY}
      - TELNYX_CONNECTION_ID=${TELNYX_CONNECTION_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - HUMAN_DETECTED_WEBHOOK_URL=${HUMAN_DETECTED_WEBHOOK_URL}
      - CALL_COMPLETED_WEBHOOK_URL=${CALL_COMPLETED_WEBHOOK_URL}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: mvp_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mvp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: